name: model-training
on:
  workflow_dispatch:
    inputs:
      epochs:
        description: 'Number of epochs'
        required: true
        default: '100'

jobs:
  train:
    runs-on: ubuntu-latest
      
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Docker-Build
        run: docker build -t my-docker-model .

      - name: Model Training
        run: docker run -e EPOCHS=${{ github.event.inputs.epochs }} my-docker-model python train.py
        
  evaluate:
    needs: [train]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Docker-Build
        run: docker build -t my-docker-model .

      - name: Model Evaluation
        run: docker run my-docker-model python prediction.py
        
  archive:
    needs: [evaluate]
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      
      - name: Archive model
        uses: actions/upload-artifact@v2
        with:
          name: model
          path: /classificationn_model.pt
