name: model-training
on:
  workflow_dispatch
  

jobs:
  train:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout-repo
        uses: actions/checkout@v2
        
      - name: Docker-Build
        run: docker build -t dockerfile .
        
      - name: train
        run: docker run -v ${PWD}:/ dockerfile python train.py --param1 ${{ github.event.inputs.train_param1 }} --param2 ${{ github.event.inputs.train_param2 }}

        
      - name: docker-Run
        run: docker run dockerfile ls -l ./
        
  evaluate:
    needs: train
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout-repo
      uses: actions/checkout@v2

    - name: Docker-Build
      run: docker build -t dockerfile .

    - name: prediction
      run: docker run -v ${PWD}:/ dockerfile python evaluate.py

